package org.dalol.amharickeyboardview;

import java.util.HashMap;
import java.util.Map;

/**
 * @author Filippo Engidashet <filippo.eng@gmail.com>
 * @version 1.0.0
 * @since 9/6/2016
 */
public class AmharicKeyMap {

//
//
//    public enum AmharicKeyTypography {
//        ETHIOPIC_SYLLABLE("ETHIOPIC SYLLABLE"),
//        ETHIOPIC_SYLLABLE_PHARYNGEAL("ETHIOPIC SYLLABLE PHARYNGEAL"),
//        ETHIOPIC_SYLLABLE_GLOTTAL("ETHIOPIC SYLLABLE GLOTTAL"),
//        ETHIOPIC_SYLLABLE("ETHIOPIC SYLLABLE");
//
//        AmharicKeyTypography(String typography) {
//
//        }
//    }
//
//    public static class AmharicKeyTypography
//
//    Map<Character, AmharicKeyTypography> keyTypographyMap = new HashMap<>();
//
//    {
//        keyTypographyMap.put()
//    }
//
//    public static class AmharicKey {
//        private char mUnicodeCharValue;
//        private char mUnicodeChar;
//        private String mKeyPronoutiation;
//    }
//
//    1200 ሀ ETHIOPIC SYLLABLE HA
//    1201 ሁ ETHIOPIC SYLLABLE HU
//    1202 ሂ ETHIOPIC SYLLABLE HI
//    1203 ሃ ETHIOPIC SYLLABLE HAA
//    1204 ሄ ETHIOPIC SYLLABLE HEE
//    1205 ህ ETHIOPIC SYLLABLE HE
//    1206 ሆ ETHIOPIC SYLLABLE HO
//    1207 ሇ ETHIOPIC SYLLABLE HOA
//    1208 ለ ETHIOPIC SYLLABLE LA
//    1209 ሉ ETHIOPIC SYLLABLE LU
//    120A ሊ ETHIOPIC SYLLABLE LI
//    120B ላ ETHIOPIC SYLLABLE LAA
//    120C ሌ ETHIOPIC SYLLABLE LEE
//    120D ል ETHIOPIC SYLLABLE LE
//    120E ሎ ETHIOPIC SYLLABLE LO
//    120F ሏ ETHIOPIC SYLLABLE LWA
//    1210 ሐ ETHIOPIC SYLLABLE HHA
//    1211 ሑ ETHIOPIC SYLLABLE HHU
//    1212 ሒ ETHIOPIC SYLLABLE HHI
//    1213 ሓ ETHIOPIC SYLLABLE HHAA
//    1214 ሔ ETHIOPIC SYLLABLE HHEE
//    1215 ሕ ETHIOPIC SYLLABLE HHE
//    1216 ሖ ETHIOPIC SYLLABLE HHO
//    1217 ሗ ETHIOPIC SYLLABLE HHWA
//    1218 መ ETHIOPIC SYLLABLE MA
//    1219 ሙ ETHIOPIC SYLLABLE MU
//    121A ሚ ETHIOPIC SYLLABLE MI
//    121B ማ ETHIOPIC SYLLABLE MAA
//    121C ሜ ETHIOPIC SYLLABLE MEE
//    121D ም ETHIOPIC SYLLABLE ME
//    121E ሞ ETHIOPIC SYLLABLE MO
//    121F ሟ ETHIOPIC SYLLABLE MWA
//    1220 ሠ ETHIOPIC SYLLABLE SZA
//    1221 ሡ ETHIOPIC SYLLABLE SZU
//    1222 ሢ ETHIOPIC SYLLABLE SZI
//    1223 ሣ ETHIOPIC SYLLABLE SZAA
//    1224 ሤ ETHIOPIC SYLLABLE SZEE
//    1225 ሥ ETHIOPIC SYLLABLE SZE
//    1226 ሦ ETHIOPIC SYLLABLE SZO
//    1227 ሧ ETHIOPIC SYLLABLE SZWA
//    1228 ረ ETHIOPIC SYLLABLE RA
//    1229 ሩ ETHIOPIC SYLLABLE RU
//    122A ሪ ETHIOPIC SYLLABLE RI
//    122B ራ ETHIOPIC SYLLABLE RAA
//    122C ሬ ETHIOPIC SYLLABLE REE
//    122D ር ETHIOPIC SYLLABLE RE
//    122E ሮ ETHIOPIC SYLLABLE RO
//    122F ሯ ETHIOPIC SYLLABLE RWA
//    1230 ሰ ETHIOPIC SYLLABLE SA
//    1231 ሱ ETHIOPIC SYLLABLE SU
//    1232 ሲ ETHIOPIC SYLLABLE SI
//    1233 ሳ ETHIOPIC SYLLABLE SAA
//    1234 ሴ ETHIOPIC SYLLABLE SEE
//    1235 ስ ETHIOPIC SYLLABLE SE
//    1236 ሶ ETHIOPIC SYLLABLE SO
//    1237 ሷ ETHIOPIC SYLLABLE SWA
//    1238 ሸ ETHIOPIC SYLLABLE SHA
//    1239 ሹ ETHIOPIC SYLLABLE SHU
//    123A ሺ ETHIOPIC SYLLABLE SHI
//    123B ሻ ETHIOPIC SYLLABLE SHAA
//    123C ሼ ETHIOPIC SYLLABLE SHEE
//    123D ሽ ETHIOPIC SYLLABLE SHE
//    123E ሾ ETHIOPIC SYLLABLE SHO
//    123F ሿ ETHIOPIC SYLLABLE SHWA
//    1240 ቀ ETHIOPIC SYLLABLE QA
//    1241 ቁ ETHIOPIC SYLLABLE QU
//    1242 ቂ ETHIOPIC SYLLABLE QI
//    1243 ቃ ETHIOPIC SYLLABLE QAA
//    1244 ቄ ETHIOPIC SYLLABLE QEE
//    1245 ቅ ETHIOPIC SYLLABLE QE
//    1246 ቆ ETHIOPIC SYLLABLE QO
//    1247 ቇ ETHIOPIC SYLLABLE QOA
//    1248 ቈ ETHIOPIC SYLLABLE QWA
//    1249 " <reserved>
//            124A ቊ ETHIOPIC SYLLABLE QWI
//    124B ቋ ETHIOPIC SYLLABLE QWAA
//    124C ቌ ETHIOPIC SYLLABLE QWEE
//    124D ቍ ETHIOPIC SYLLABLE QWE
//    124E " <reserved>
//            124F " <reserved>
//            1250 ቐ ETHIOPIC SYLLABLE QHA
//    1251 ቑ ETHIOPIC SYLLABLE QHU
//    1252 ቒ ETHIOPIC SYLLABLE QHI
//    1253 ቓ ETHIOPIC SYLLABLE QHAA
//    1254 ቔ ETHIOPIC SYLLABLE QHEE
//    1255 ቕ ETHIOPIC SYLLABLE QHE
//    1256 ቖ ETHIOPIC SYLLABLE QHO
//    1257 " <reserved>
//            1258 ቘ ETHIOPIC SYLLABLE QHWA
//    1259 " <reserved>
//            125A ቚ ETHIOPIC SYLLABLE QHWI
//    125B ቛ ETHIOPIC SYLLABLE QHWAA
//    125C ቜ ETHIOPIC SYLLABLE QHWEE
//    125D ቝ ETHIOPIC SYLLABLE QHWE
//    125E " <reserved>
//            125F " <reserved>
//            1260 በ ETHIOPIC SYLLABLE BA
//    1261 ቡ ETHIOPIC SYLLABLE BU
//    1262 ቢ ETHIOPIC SYLLABLE BI
//    1263 ባ ETHIOPIC SYLLABLE BAA
//    1264 ቤ ETHIOPIC SYLLABLE BEE
//    1265 ብ ETHIOPIC SYLLABLE BE
//    1266 ቦ ETHIOPIC SYLLABLE BO
//    1267 ቧ ETHIOPIC SYLLABLE BWA
//    1268 ቨ ETHIOPIC SYLLABLE VA
//    1269 ቩ ETHIOPIC SYLLABLE VU
//    126A ቪ ETHIOPIC SYLLABLE VI
//    126B ቫ ETHIOPIC SYLLABLE VAA
//    126C ቬ ETHIOPIC SYLLABLE VEE
//    126D ቭ ETHIOPIC SYLLABLE VE
//    126E ቮ ETHIOPIC SYLLABLE VO
//    126F ቯ ETHIOPIC SYLLABLE VWA
//    1270 ተ ETHIOPIC SYLLABLE TA
//    1271 ቱ ETHIOPIC SYLLABLE TU
//    1272 ቲ ETHIOPIC SYLLABLE TI
//    1273 ታ ETHIOPIC SYLLABLE TAA
//    1274 ቴ ETHIOPIC SYLLABLE TEE
//    1275 ት ETHIOPIC SYLLABLE TE
//    1276 ቶ ETHIOPIC SYLLABLE TO
//    1277 ቷ ETHIOPIC SYLLABLE TWA
//    1278 ቸ ETHIOPIC SYLLABLE CA
//    1279 ቹ ETHIOPIC SYLLABLE CU
//
//
//
//    127A Ethiopic 12F5
//            12B8 ኸ ETHIOPIC SYLLABLE KXA
//    12B9 ኹ ETHIOPIC SYLLABLE KXU
//    12BA ኺ ETHIOPIC SYLLABLE KXI
//    12BB ኻ ETHIOPIC SYLLABLE KXAA
//    12BC ኼ ETHIOPIC SYLLABLE KXEE
//    12BD ኽ ETHIOPIC SYLLABLE KXE
//    12BE ኾ ETHIOPIC SYLLABLE KXO
//    12BF " <reserved>
//            12C0 ዀ ETHIOPIC SYLLABLE KXWA
//    12C1 " <reserved>
//            12C2 ዂ ETHIOPIC SYLLABLE KXWI
//    12C3 ዃ ETHIOPIC SYLLABLE KXWAA
//    12C4 ዄ ETHIOPIC SYLLABLE KXWEE
//    12C5 ዅ ETHIOPIC SYLLABLE KXWE
//    12C6 " <reserved>
//            12C7 " <reserved>
//            12C8 ወ ETHIOPIC SYLLABLE WA
//    12C9 ዉ ETHIOPIC SYLLABLE WU
//    12CA ዊ ETHIOPIC SYLLABLE WI
//    12CB ዋ ETHIOPIC SYLLABLE WAA
//    12CC ዌ ETHIOPIC SYLLABLE WEE
//    12CD ው ETHIOPIC SYLLABLE WE
//    12CE ዎ ETHIOPIC SYLLABLE WO
//    12CF ዏ ETHIOPIC SYLLABLE WOA
//    12D0 ዐ ETHIOPIC SYLLABLE PHARYNGEAL A
//    12D1 ዑ ETHIOPIC SYLLABLE PHARYNGEAL U
//    12D2 ዒ ETHIOPIC SYLLABLE PHARYNGEAL I
//    12D3 ዓ ETHIOPIC SYLLABLE PHARYNGEAL AA
//    12D4 ዔ ETHIOPIC SYLLABLE PHARYNGEAL EE
//    12D5 ዕ ETHIOPIC SYLLABLE PHARYNGEAL E
//    12D6 ዖ ETHIOPIC SYLLABLE PHARYNGEAL O
//    12D7 " <reserved>
//            12D8 ዘ ETHIOPIC SYLLABLE ZA
//    12D9 ዙ ETHIOPIC SYLLABLE ZU
//    12DA ዚ ETHIOPIC SYLLABLE ZI
//    12DB ዛ ETHIOPIC SYLLABLE ZAA
//    12DC ዜ ETHIOPIC SYLLABLE ZEE
//    12DD ዝ ETHIOPIC SYLLABLE ZE
//    12DE ዞ ETHIOPIC SYLLABLE ZO
//    12DF ዟ ETHIOPIC SYLLABLE ZWA
//    12E0 ዠ ETHIOPIC SYLLABLE ZHA
//    12E1 ዡ ETHIOPIC SYLLABLE ZHU
//    12E2 ዢ ETHIOPIC SYLLABLE ZHI
//    12E3 ዣ ETHIOPIC SYLLABLE ZHAA
//    12E4 ዤ ETHIOPIC SYLLABLE ZHEE
//    12E5 ዥ ETHIOPIC SYLLABLE ZHE
//    12E6 ዦ ETHIOPIC SYLLABLE ZHO
//    12E7 ዧ ETHIOPIC SYLLABLE ZHWA
//    12E8 የ ETHIOPIC SYLLABLE YA
//    12E9 ዩ ETHIOPIC SYLLABLE YU
//    12EA ዪ ETHIOPIC SYLLABLE YI
//    12EB ያ ETHIOPIC SYLLABLE YAA
//    12EC ዬ ETHIOPIC SYLLABLE YEE
//    12ED ይ ETHIOPIC SYLLABLE YE
//    12EE ዮ ETHIOPIC SYLLABLE YO
//    12EF ዯ ETHIOPIC SYLLABLE YOA
//    12F0 ደ ETHIOPIC SYLLABLE DA
//    12F1 ዱ ETHIOPIC SYLLABLE DU
//    12F2 ዲ ETHIOPIC SYLLABLE DI
//    12F3 ዳ ETHIOPIC SYLLABLE DAA
//    12F4 ዴ ETHIOPIC SYLLABLE DEE
//    12F5 ድ ETHIOPIC SYLLABLE DE
//    127A ቺ ETHIOPIC SYLLABLE CI
//    127B ቻ ETHIOPIC SYLLABLE CAA
//    127C ቼ ETHIOPIC SYLLABLE CEE
//    127D ች ETHIOPIC SYLLABLE CE
//    127E ቾ ETHIOPIC SYLLABLE CO
//    127F ቿ ETHIOPIC SYLLABLE CWA
//    1280 ኀ ETHIOPIC SYLLABLE XA
//    1281 ኁ ETHIOPIC SYLLABLE XU
//    1282 ኂ ETHIOPIC SYLLABLE XI
//    1283 ኃ ETHIOPIC SYLLABLE XAA
//    1284 ኄ ETHIOPIC SYLLABLE XEE
//    1285 ኅ ETHIOPIC SYLLABLE XE
//    1286 ኆ ETHIOPIC SYLLABLE XO
//    1287 ኇ ETHIOPIC SYLLABLE XOA
//    1288 ኈ ETHIOPIC SYLLABLE XWA
//    1289 " <reserved>
//            128A ኊ ETHIOPIC SYLLABLE XWI
//    128B ኋ ETHIOPIC SYLLABLE XWAA
//    128C ኌ ETHIOPIC SYLLABLE XWEE
//    128D ኍ ETHIOPIC SYLLABLE XWE
//    128E " <reserved>
//            128F " <reserved>
//            1290 ነ ETHIOPIC SYLLABLE NA
//    1291 ኑ ETHIOPIC SYLLABLE NU
//    1292 ኒ ETHIOPIC SYLLABLE NI
//    1293 ና ETHIOPIC SYLLABLE NAA
//    1294 ኔ ETHIOPIC SYLLABLE NEE
//    1295 ን ETHIOPIC SYLLABLE NE
//    1296 ኖ ETHIOPIC SYLLABLE NO
//    1297 ኗ ETHIOPIC SYLLABLE NWA
//    1298 ኘ ETHIOPIC SYLLABLE NYA
//    1299 ኙ ETHIOPIC SYLLABLE NYU
//    129A ኚ ETHIOPIC SYLLABLE NYI
//    129B ኛ ETHIOPIC SYLLABLE NYAA
//    129C ኜ ETHIOPIC SYLLABLE NYEE
//    129D ኝ ETHIOPIC SYLLABLE NYE
//    129E ኞ ETHIOPIC SYLLABLE NYO
//    129F ኟ ETHIOPIC SYLLABLE NYWA
//    12A0 አ ETHIOPIC SYLLABLE GLOTTAL A
//    12A1 ኡ ETHIOPIC SYLLABLE GLOTTAL U
//    12A2 ኢ ETHIOPIC SYLLABLE GLOTTAL I
//    12A3 ኣ ETHIOPIC SYLLABLE GLOTTAL AA
//    12A4 ኤ ETHIOPIC SYLLABLE GLOTTAL EE
//    12A5 እ ETHIOPIC SYLLABLE GLOTTAL E
//    12A6 ኦ ETHIOPIC SYLLABLE GLOTTAL O
//    12A7 ኧ ETHIOPIC SYLLABLE GLOTTAL WA
//    12A8 ከ ETHIOPIC SYLLABLE KA
//    12A9 ኩ ETHIOPIC SYLLABLE KU
//    12AA ኪ ETHIOPIC SYLLABLE KI
//    12AB ካ ETHIOPIC SYLLABLE KAA
//    12AC ኬ ETHIOPIC SYLLABLE KEE
//    12AD ክ ETHIOPIC SYLLABLE KE
//    12AE ኮ ETHIOPIC SYLLABLE KO
//    12AF ኯ ETHIOPIC SYLLABLE KOA
//    12B0 ኰ ETHIOPIC SYLLABLE KWA
//    12B1 " <reserved>
//            12B2 ኲ ETHIOPIC SYLLABLE KWI
//    12B3 ኳ ETHIOPIC SYLLABLE KWAA
//    12B4 ኴ ETHIOPIC SYLLABLE KWEE
//    12B5 ኵ ETHIOPIC SYLLABLE KWE
//    12B6 " <reserved>
//            12B7 " <reserved>
//    The Unicode Standard 9.0, Copyright © 1991-2016 Unicode, Inc. All rights reserved.
//    12F6 Ethiopic 136B
//    1334 ጴ ETHIOPIC SYLLABLE PHEE
//    1335 ጵ ETHIOPIC SYLLABLE PHE
//    1336 ጶ ETHIOPIC SYLLABLE PHO
//    1337 ጷ ETHIOPIC SYLLABLE PHWA
//    1338 ጸ ETHIOPIC SYLLABLE TSA
//    1339 ጹ ETHIOPIC SYLLABLE TSU
//    133A ጺ ETHIOPIC SYLLABLE TSI
//    133B ጻ ETHIOPIC SYLLABLE TSAA
//    133C ጼ ETHIOPIC SYLLABLE TSEE
//    133D ጽ ETHIOPIC SYLLABLE TSE
//    133E ጾ ETHIOPIC SYLLABLE TSO
//    133F ጿ ETHIOPIC SYLLABLE TSWA
//    1340 ፀ ETHIOPIC SYLLABLE TZA
//    1341 ፁ ETHIOPIC SYLLABLE TZU
//    1342 ፂ ETHIOPIC SYLLABLE TZI
//    1343 ፃ ETHIOPIC SYLLABLE TZAA
//    1344 ፄ ETHIOPIC SYLLABLE TZEE
//    1345 ፅ ETHIOPIC SYLLABLE TZE
//    1346 ፆ ETHIOPIC SYLLABLE TZO
//    1347 ፇ ETHIOPIC SYLLABLE TZOA
//    1348 ፈ ETHIOPIC SYLLABLE FA
//    1349 ፉ ETHIOPIC SYLLABLE FU
//    134A ፊ ETHIOPIC SYLLABLE FI
//    134B ፋ ETHIOPIC SYLLABLE FAA
//    134C ፌ ETHIOPIC SYLLABLE FEE
//    134D ፍ ETHIOPIC SYLLABLE FE
//    134E ፎ ETHIOPIC SYLLABLE FO
//    134F ፏ ETHIOPIC SYLLABLE FWA
//    1350 ፐ ETHIOPIC SYLLABLE PA
//    1351 ፑ ETHIOPIC SYLLABLE PU
//    1352 ፒ ETHIOPIC SYLLABLE PI
//    1353 ፓ ETHIOPIC SYLLABLE PAA
//    1354 ፔ ETHIOPIC SYLLABLE PEE
//    1355 ፕ ETHIOPIC SYLLABLE PE
//    1356 ፖ ETHIOPIC SYLLABLE PO
//    1357 ፗ ETHIOPIC SYLLABLE PWA
//    1358 ፘ ETHIOPIC SYLLABLE RYA
//    1359 ፙ ETHIOPIC SYLLABLE MYA
//    135A ፚ ETHIOPIC SYLLABLE FYA
//    Combining marks
//    135D $ ETHIOPIC COMBINING GEMINATION AND
//    VOWEL LENGTH MARK
//    • Basketo
//    135E $ ETHIOPIC COMBINING VOWEL LENGTH MARK
//    • Basketo
//    135F $፟ ETHIOPIC COMBINING GEMINATION MARK
//            Punctuation
//    1360 ፠ ETHIOPIC SECTION MARK
//    1361 ፡ ETHIOPIC WORDSPACE
//    1362 ። ETHIOPIC FULL STOP
//    1363 ፣ ETHIOPIC COMMA
//    1364 ፤ ETHIOPIC SEMICOLON
//    1365 ፥ ETHIOPIC COLON
//    1366 ፦ ETHIOPIC PREFACE COLON
//    1367 ፧ ETHIOPIC QUESTION MARK
//    1368 ፨ ETHIOPIC PARAGRAPH SEPARATOR
//            Digits
//    1369 ፩ ETHIOPIC DIGIT ONE
//    136A ፪ ETHIOPIC DIGIT TWO
//    136B ፫ ETHIOPIC DIGIT THREE
//    12F6 ዶ ETHIOPIC SYLLABLE DO
//    12F7 ዷ ETHIOPIC SYLLABLE DWA
//    12F8 ዸ ETHIOPIC SYLLABLE DDA
//    12F9 ዹ ETHIOPIC SYLLABLE DDU
//    12FA ዺ ETHIOPIC SYLLABLE DDI
//    12FB ዻ ETHIOPIC SYLLABLE DDAA
//    12FC ዼ ETHIOPIC SYLLABLE DDEE
//    12FD ዽ ETHIOPIC SYLLABLE DDE
//    12FE ዾ ETHIOPIC SYLLABLE DDO
//    12FF ዿ ETHIOPIC SYLLABLE DDWA
//    1300 ጀ ETHIOPIC SYLLABLE JA
//    1301 ጁ ETHIOPIC SYLLABLE JU
//    1302 ጂ ETHIOPIC SYLLABLE JI
//    1303 ጃ ETHIOPIC SYLLABLE JAA
//    1304 ጄ ETHIOPIC SYLLABLE JEE
//    1305 ጅ ETHIOPIC SYLLABLE JE
//    1306 ጆ ETHIOPIC SYLLABLE JO
//    1307 ጇ ETHIOPIC SYLLABLE JWA
//    1308 ገ ETHIOPIC SYLLABLE GA
//    1309 ጉ ETHIOPIC SYLLABLE GU
//    130A ጊ ETHIOPIC SYLLABLE GI
//    130B ጋ ETHIOPIC SYLLABLE GAA
//    130C ጌ ETHIOPIC SYLLABLE GEE
//    130D ግ ETHIOPIC SYLLABLE GE
//    130E ጎ ETHIOPIC SYLLABLE GO
//    130F ጏ ETHIOPIC SYLLABLE GOA
//    1310 ጐ ETHIOPIC SYLLABLE GWA
//    1311 " <reserved>
//            1312 ጒ ETHIOPIC SYLLABLE GWI
//    1313 ጓ ETHIOPIC SYLLABLE GWAA
//    1314 ጔ ETHIOPIC SYLLABLE GWEE
//    1315 ጕ ETHIOPIC SYLLABLE GWE
//    1316 " <reserved>
//            1317 " <reserved>
//            1318 ጘ ETHIOPIC SYLLABLE GGA
//    1319 ጙ ETHIOPIC SYLLABLE GGU
//    131A ጚ ETHIOPIC SYLLABLE GGI
//    131B ጛ ETHIOPIC SYLLABLE GGAA
//    131C ጜ ETHIOPIC SYLLABLE GGEE
//    131D ጝ ETHIOPIC SYLLABLE GGE
//    131E ጞ ETHIOPIC SYLLABLE GGO
//    131F ጟ ETHIOPIC SYLLABLE GGWAA
//    1320 ጠ ETHIOPIC SYLLABLE THA
//    1321 ጡ ETHIOPIC SYLLABLE THU
//    1322 ጢ ETHIOPIC SYLLABLE THI
//    1323 ጣ ETHIOPIC SYLLABLE THAA
//    1324 ጤ ETHIOPIC SYLLABLE THEE
//    1325 ጥ ETHIOPIC SYLLABLE THE
//    1326 ጦ ETHIOPIC SYLLABLE THO
//    1327 ጧ ETHIOPIC SYLLABLE THWA
//    1328 ጨ ETHIOPIC SYLLABLE CHA
//    1329 ጩ ETHIOPIC SYLLABLE CHU
//    132A ጪ ETHIOPIC SYLLABLE CHI
//    132B ጫ ETHIOPIC SYLLABLE CHAA
//    132C ጬ ETHIOPIC SYLLABLE CHEE
//    132D ጭ ETHIOPIC SYLLABLE CHE
//    132E ጮ ETHIOPIC SYLLABLE CHO
//    132F ጯ ETHIOPIC SYLLABLE CHWA
//    1330 ጰ ETHIOPIC SYLLABLE PHA
//    1331 ጱ ETHIOPIC SYLLABLE PHU
//    1332 ጲ ETHIOPIC SYLLABLE PHI
//    1333 ጳ ETHIOPIC SYLLABLE PHAA
//    The Unicode Standard 9.0, Copyright © 1991-2016 Unicode, Inc. All rights reserved.
//    136C Ethiopic 137C
//    136C ፬ ETHIOPIC DIGIT FOUR
//    136D ፭ ETHIOPIC DIGIT FIVE
//    136E ፮ ETHIOPIC DIGIT SIX
//    136F ፯ ETHIOPIC DIGIT SEVEN
//    1370 ፰ ETHIOPIC DIGIT EIGHT
//    1371 ፱ ETHIOPIC DIGIT NINE
//            Numbers
//    1372 ፲ ETHIOPIC NUMBER TEN
//    1373 ፳ ETHIOPIC NUMBER TWENTY
//    1374 ፴ ETHIOPIC NUMBER THIRTY
//    1375 ፵ ETHIOPIC NUMBER FORTY
//    1376 ፶ ETHIOPIC NUMBER FIFTY
//    1377 ፷ ETHIOPIC NUMBER SIXTY
//    1378 ፸ ETHIOPIC NUMBER SEVENTY
//    1379 ፹ ETHIOPIC NUMBER EIGHTY
//    137A ፺ ETHIOPIC NUMBER NINETY
//    137B ፻ ETHIOPIC NUMBER HUNDRED
//    137C ፼ ETHIOPIC NUMBER TEN THOUSAND
}
